[credentials]
usernames = ["admin", "analyst"]

[credentials.admin]
name = "Hari Admin"
password = "$2b$12$wJrg1CJyWh86S7pobXY5eOAeI4jBJ.3w09dTe3y.fDwWVL7gEthTm"

[credentials.analyst]
name = "Data Analyst"
password = "$2b$12$9cZp...hashed_bcrypt_password_here"

[cookie]
name = "aio_auth"
key = "a-very-long-random-key"
expiry_days = 7

#[preauthorized]
#emails = ["your.name@company.com"]
